language: node_js
node_js:
  - 8

install: npm ci

env: URL=https://wearesho.com

script:
  - BUILD_TIME=$(TZ=":Europe/Kiev" date '+%Y-%m-%d %H:%M:%S %z') npm run build && cp dist/index.html dist/404.html

after_deploy:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Wearesho%20site%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%20Succeeded%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22%0A${URL}" npm run coverage

after_failure:
  - curl --request GET "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=Wearesho%20site%0ABuild%20%23${TRAVIS_BUILD_NUMBER}.%20Failed%0ACommit:%20%22${TRAVIS_COMMIT_MESSAGE}%22"

cache:
  npm: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ./dist
  fqdn: $URL
